### ISSUE TITLE
how to find only football court area using opencv

### ISSUE THREAD

**Issue by Razamalik4497** [ArunJayan/OpenCV-Python#1]
![1](https://github.com/ArunJayan/OpenCV-Python/assets/49755089/41ae011c-3be5-420c-b9ec-79ffae191c63)

**Comment by Razamalik4497** [comment]
![2](https://github.com/ArunJayan/OpenCV-Python/assets/49755089/a7fbd93b-71c2-45a1-8f62-e5001e5eb6ca)

**Comment by ArunJayan** [comment]
Hi @Razamalik4497 

To get started with the task of detecting the football court, you can follow these steps as a starting point. 
Convert the image to the HSV color space and define a range of hue values for green. 
Create a mask based on the hue component and refine it using morphological operations. 
Apply the refined mask to extract the green football court area.
